INSERT INTO `master_documents` VALUES (1, '', 'MASTER B/L', 'MB/L', NULL, NULL, '2017-9-8 07:28:42', '2017-9-8 07:28:42');
INSERT INTO `master_documents` VALUES (2, '', 'HOUSE B/L', 'HB/L', NULL, NULL, '2017-9-8 07:28:42', '2017-9-8 07:28:42');
INSERT INTO `master_documents` VALUES (3, '', 'PART OF B/L', 'PART OFF', NULL, NULL, '2017-9-8 07:28:42', '2017-9-8 07:28:42');
INSERT INTO `master_documents` VALUES (4, '', 'PEB', 'PEB', NULL, NULL, '2017-9-8 07:28:42', '2017-9-8 07:28:42');
INSERT INTO `master_documents` VALUES (5, '', 'SPLIT B/L', 'SPLIT', NULL, NULL, '2017-9-8 07:28:42', '2017-9-8 07:28:42');
INSERT INTO `master_documents` VALUES (6, '', 'DELIVERY ORDER', 'DO', NULL, NULL, '2017-9-8 07:28:42', '2017-9-8 07:28:42');
INSERT INTO `master_documents` VALUES (7, '', 'CONTAINER AND SEAL', 'CONTAINER', NULL, NULL, '2017-9-8 07:28:42', '2017-9-8 07:28:42');

INSERT INTO `master_documents` VALUES (355, '	PB-00001	', 'OCEAN FREIGHT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (356, '	PB-00002	', 'THC - DESTINATION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (357, '	PB-00003	', 'B/L FEE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (358, '	PB-00004	', 'SWITCH B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (359, '	PB-00005	', 'TRUCKING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (360, '	PB-00006	', 'STORAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (361, '	PB-00007	', 'PEB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (362, '	PB-00008	', 'PNBP', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (363, '	PB-00009	', 'C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (364, '	PB-00010	', 'R/C', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (365, '	PB-00011	', 'TELEX', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (366, '	PB-00012	', 'CBS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (367, '	PB-00013	', 'COD', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (368, '	PB-00014	', 'B/L PART OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (369, '	PB-00015	', 'CFS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (370, '	PB-00016	', 'PU', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (371, '	PB-00017	', 'D/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (372, '	PB-00018	', 'DOCUMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (373, '	PB-00019	', 'HANDLING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (374, '	PB-00020	', 'COV', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (375, '	PB-00021	', 'SEAWAY BILL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (376, '	PB-00022	', 'UNDERNAME', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (377, '	PB-00023	', 'EXTRA INP CNTN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (378, '	PB-00024	', 'REBATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (379, '	PB-00025	', 'PROFIT SHARE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (380, '	PB-00026	', 'INSURANCE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (381, '	PB-00027	', 'SEAL FEE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (382, '	PB-00028	', 'LIFT ON', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (383, '	PB-00029	', 'LIFT OFF + PORT STORAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (384, '	PB-00030	', 'TRUCKING + C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (385, '	PB-00031	', 'AMENDMENT B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (386, '	PB-00032	', 'LOLO+ STORAGE + EDI + ADM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (387, '	PB-00033	', 'STAMP CORRECTION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (388, '	PB-00034	', 'REISSUE B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (389, '	PB-00035	', 'MEKANIK', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (390, '	PB-00036	', 'SURVEYOR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (391, '	PB-00037	', 'SUCOFINDO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (392, '	PB-00038	', 'DETENTION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (393, '	PB-00039	', 'REVISE C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (394, '	PB-00040	', 'PEMBUATAN NIK', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (395, '	PB-00041	', 'AMENDMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (396, '	PB-00042	', 'TRUCKING + PHYTOSANITARY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (397, '	PB-00043	', 'LEGALISIR INVOICE + PACKING LIST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (398, '	PB-00044	', 'TRANSFER EDI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (399, '	PB-00045	', 'EXTRA AMBIL GENSET', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (400, '	PB-00046	', 'TMBK CLS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (401, '	PB-00047	', 'MANIFEST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (402, '	PB-00048	', 'RATE + UNDERNAME + TRUCKING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (403, '	PB-00049	', 'COMBINE B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (404, '	PB-00050	', 'PEMBATALAN TRUCKING + PHYTO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (405, '	PB-00051	', 'EXTRA COLOKAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (406, '	PB-00052	', 'SOLAR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (407, '	PB-00053	', 'LIFT ON/OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (408, '	PB-00054	', 'REEFER PREPARATOR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (409, '	PB-00055	', 'COPY B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (410, '	PB-00056	', 'OCEAN FREIGHT + SWITCH B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (411, '	PB-00057	', 'COURIER FEE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (412, '	PB-00058	', 'LEGALISIR B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (413, '	PB-00059	', 'REISSUE C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (414, '	PB-00060	', 'FUMIGASI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (415, '	PB-00061	', 'STEVEDORING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (416, '	PB-00062	', 'MATERAI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (417, '	PB-00063	', 'RENOMINATION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (418, '	PB-00064	', 'REDOCUMENTATION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (419, '	PB-00065	', 'REPRINT B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (420, '	PB-00066	', 'DG CARGO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (421, '	PB-00067	', 'ALIH KAPAL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (422, '	PB-00068	', 'CANCEL PEB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (423, '	PB-00069	', 'ISPS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (424, '	PB-00070	', 'LIFT ON/OFF + STORAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (425, '	PB-00071	', 'KARANTINA', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (426, '	PB-00072	', 'DAFTAR PHYTOSANITARY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (427, '	PB-00073	', 'CERTIFICATE PHYTOSANITARY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (428, '	PB-00074	', 'TEMBAK DOKUMEN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (429, '	PB-00075	', 'INCOMING CHARGES', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (430, '	PB-00076	', 'ENS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (431, '	PB-00077	', 'KITE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (432, '	PB-00078	', 'ADDITIONAL FREE TIME', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (433, '	PB-00079	', 'LOCAL CHARGES', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (434, '	PB-00080	', 'TAX', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (435, '	PB-00081	', 'LEGALISIR C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (436, '	PB-00082	', 'DEMMURAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (437, '	PB-00083	', 'SPLIT B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (438, '	PB-00084	', 'LEMBUR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (439, '	PB-00085	', 'TRUCKING + LOLO + STORAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (440, '	PB-00086	', 'EXTRA TRUCKING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (441, '	PB-00087	', 'PBM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (442, '	PB-00088	', 'CERTIFICATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (443, '	PB-00089	', 'CERTIFICATE FREE TIME', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (444, '	PB-00090	', 'LPBC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (445, '	PB-00091	', 'ACC PELAYARAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (446, '	PB-00092	', 'HANDLING + PEB + PART OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (447, '	PB-00093	', 'MISCH CHARGES', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (448, '	PB-00094	', 'TRUCKING + HANDLING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (449, '	PB-00095	', 'TRUCKING CANCEL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (450, '	PB-00096	', 'REPO CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (451, '	PB-00097	', 'TRUCKING REPO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (452, '	PB-00098	', 'LATE TIME SI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (453, '	PB-00099	', 'ADM EXPORT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (454, '	PB-00100	', 'ADM BANK', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (455, '	PB-00101	', 'AIR FREIGHT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (456, '	PB-00102	', 'OVERTIME', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (457, '	PB-00103	', 'B/L FEE + ADM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (458, '	PB-00104	', 'OVERWEIGHT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (459, '	PB-00105	', 'ADM COD', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (460, '	PB-00106	', 'ERS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (461, '	PB-00107	', 'PPH23', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (462, '	PB-00108	', 'PEB + PART OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (463, '	PB-00109	', 'THC + BL + ADM + ETC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (464, '	PB-00110	', 'PDE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (465, '	PB-00111	', 'DISCRIPENSI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (466, '	PB-00112	', 'TRUCKING + LOLO + STORAGE + PEB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (467, '	PB-00113	', 'DG SURCHARGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (468, '	PB-00114	', 'SMD', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (469, '	PB-00115	', 'DEVANNING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (470, '	PB-00116	', 'REPRINT C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (471, '	PB-00117	', 'ADM + LIFT ON CANCEL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (472, '	PB-00118	', 'OPBC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (473, '	PB-00119	', 'ADM + D/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (474, '	PB-00120	', 'RDM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (475, '	PB-00121	', 'WAREHOUSE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (476, '	PB-00122	', 'STUFFING + LAXING + HANDLING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (477, '	PB-00123	', 'DOCUMENT EXPORT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (478, '	PB-00124	', 'FORM C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (479, '	PB-00125	', 'PECAH POS UMUM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (480, '	PB-00126	', 'TEMBAK KARTU KUNING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (481, '	PB-00127	', 'MCF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (482, '	PB-00128	', 'MUTUAL PROFIT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (483, '	PB-00129	', 'OCEAN FREIGHT + DTHC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (484, '	PB-00130	', 'CONGESTION FEE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (485, '	PB-00131	', 'LOLO + STORAGE + EDI + ADM CANCEL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (486, '	PB-00132	', 'REHANDLING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (487, '	PB-00133	', 'CANCEL LIFT ON/OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (488, '	PB-00134	', 'LEMBUR DEPO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (489, '	PB-00135	', 'MUTUAL SHARE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (490, '	PB-00136	', 'INLAND', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (491, '	PB-00137	', 'LATE FINAL DOCUMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (492, '	PB-00138	', 'TAMBAHAN UANG JALAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (493, '	PB-00139	', 'LATE FINAL SI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (494, '	PB-00140	', 'FREE TIME DETENTION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (495, '	PB-00141	', 'AMF MANIFEST + CARGO DEC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (496, '	PB-00142	', 'CUSTOM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (497, '	PB-00143	', 'OVERWEIGHT SURCHARGES', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (498, '	PB-00144	', 'TUSLAH', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (499, '	PB-00145	', 'PPN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (500, '	PB-00146	', 'TEMBAK C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (501, '	PB-00147	', 'PORT HANDLING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (502, '	PB-00148	', 'UANG JALAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (503, '	PB-00149	', 'BEA KELUAR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (504, '	PB-00150	', 'LEGALISIR SCCP', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (505, '	PB-00151	', 'SURVEI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (506, '	PB-00152	', 'D/O MUAT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (507, '	PB-00153	', 'LATE MODIFICATION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (508, '	PB-00154	', 'COSTEM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (509, '	PB-00155	', 'ISPKA C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (510, '	PB-00156	', 'INSPECTION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (511, '	PB-00157	', 'LEGALISIR C/O DEPHAM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (512, '	PB-00158	', 'LEGALISIR C/O DEPLU', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (513, '	PB-00159	', 'LEGALISIR C/O EMBASSY QATAR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (514, '	PB-00160	', 'OVERTIME TRUCKING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (515, '	PB-00161	', 'IP', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (516, '	PB-00162	', 'TEMBAK C/O IP', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (517, '	PB-00163	', 'CORECTION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (518, '	PB-00164	', 'SHIFTING COST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (519, '	PB-00165	', 'REPRINT SWITCH B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (520, '	PB-00166	', 'COSTEM HANDLING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (521, '	PB-00167	', 'LEGALISIR PEB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (522, '	PB-00168	', 'LAXING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (523, '	PB-00169	', 'LIFT OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (524, '	PB-00170	', 'DEPO PERTAMA', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (525, '	PB-00171	', 'AFA', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (526, '	PB-00172	', 'PSS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (527, '	PB-00173	', 'PART OFF B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (528, '	PB-00174	', 'TSC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (529, '	PB-00175	', 'LIFT ON + SEAL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (530, '	PB-00176	', 'DTHC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (531, '	PB-00177	', 'EARLY STACKING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (532, '	PB-00178	', 'PRINT EIR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (533, '	PB-00179	', 'THC - ORIGIN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (534, '	PB-00180	', 'KAWALAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (535, '	PB-00181	', 'KURANG BAYAR OCEAN FREIGHT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (536, '	PB-00182	', 'AMS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (537, '	PB-00183	', 'EXPORT FEE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (538, '	PB-00184	', 'COST RECOVERY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (539, '	PB-00185	', 'BURUH', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (540, '	PB-00186	', 'COURIER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (541, '	PB-00187	', 'KURANG BAYAR ADM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (542, '	PB-00188	', 'KURANG BAYAR C/O', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (543, '	PB-00189	', 'READRESS MANIFEST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (544, '	PB-00190	', 'RO RO CARGO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (545, '	PB-00191	', 'MANIFEST AMENDMENT FEE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (546, '	PB-00192	', 'HANDAL JAYA', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (547, '	PB-00193	', 'REDRESS MANIFEST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (548, '	PB-00194	', 'AFS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (549, '	PB-00195	', 'SEWA GENSET', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (550, '	PB-00196	', 'SCS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (551, '	PB-00197	', 'FORWARDING CHARGES', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (552, '	PB-00198	', 'PENALTY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (553, '	PB-00199	', 'ISS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (554, '	PB-00200	', 'BIAYA KURIR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (555, '	PB-00201	', 'SEQURITY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (556, '	PB-00202	', 'BIAYA PRINT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (557, '	PB-00203	', 'KURANG BAYAR MANIFEST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (558, '	PB-00204	', 'KURANG BAYAR SWITCH B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (559, '	PB-00205	', 'KURANG BAYAR SEAL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (560, '	PB-00206	', 'KURANG BAYAR THC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (561, '	PB-00207	', 'KURANG BAYAR REPRINT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (562, '	PB-00208	', 'KURANG BAYAR B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (563, '	PB-00209	', 'TEMBAK CLOSING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (564, '	PB-00210	', 'TARIK CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (565, '	PB-00211	', 'CANCEL EXPORT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (566, '	PB-00212	', 'KURANG BAYAR CERTIFICATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (567, '	PB-00213	', 'PPN MASUKAN B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (568, '	PB-00214	', 'PPN MASUKAN ADM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (569, '	PB-00215	', 'PART OFF PEB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (570, '	PB-00216	', 'FLATFILE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (571, '	PB-00217	', 'PPN MASUKAN CERTIFICATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (572, '	PB-00218	', 'PPN MASUKAN SWITCH B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (573, '	PB-00219	', 'LATE PICK UP B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (574, '	PB-00220	', 'BIAYA SURAT PERNYATAAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (575, '	PB-00221	', 'SSC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (576, '	PB-00222	', 'FSC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (577, '	PB-00223	', 'MAWB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (578, '	PB-00224	', 'DIV FEE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (579, '	PB-00225	', 'PAI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (580, '	PB-00226	', 'PPN MASUKAN AMENDMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (581, '	PB-00227	', 'PPN MASUKAN REISSUE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (582, '	PB-00228	', 'PPN MASUKAN MANIFEST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (583, '	PB-00229	', 'EMI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (584, '	PB-00230	', 'PPN MASUKAN ADM COD', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (585, '	PB-00231	', 'DOC FEE HAZARDOUS CARGO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (586, '	PB-00232	', 'PPN MASUKAN DOC FEE HAZARDOUS CARGO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (587, '	PB-00233	', 'HAZARDOUS DOC LODGEMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (588, '	PB-00234	', 'APEX MARITIME CO INC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (589, 'PB-00235', 'BIAYA KARTU PAS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (590, 'PB-00236', 'PORT ADDITIONAL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (591, 'PB-00237', 'SFS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (592, 'PB-00238', 'CGO DECLAT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (593, 'PB-00239', 'BIAYA SEAL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (594, 'PB-00240', 'ADEN GULF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (595, 'PB-00241', 'COMBO TRUCKING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (596, 'PB-00242', 'GOVERNMENT AGENCY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (597, 'PB-00243', 'KURANG BAYAR TELEX', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (598, 'PB-00244', 'BIAYA FOTOCOPY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (599, 'PB-00245', 'LOLO STORAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (600, 'PB-00246', 'PPN MASUKAN TELEX', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (601, 'PB-00247', 'PT. GIHON INTERNATIONAL CARGO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (602, 'PB-00248', 'DESTINATION CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (603, 'PB-00249', 'OCEAN FREIGHT ( IMPORT )', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (604, 'PB-00251', 'PPN MASUKAN FUMIGASI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (605, 'PB-00252', 'ACC PELAYARAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (606, 'PB-00253', 'BIAYA TIMBANG ISI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (607, 'PB-00254', 'BIAYA TIMBANG KOSONG', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (608, 'PB-00255', 'BIAYA CANCEL KARANTINA', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (609, 'PB-00256', 'SSD', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (610, 'PB-00257', 'BIAYA TRANSPORT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (611, 'PB-00258', 'PEMBATALAN PEB & UNDERNAME', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (612, 'PB-00259', 'ACE-M1', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (613, 'PB-00260', 'APF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (614, 'PB-00261', 'OTHER CHARGES', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (615, 'PB-00262', 'EXTEND CLOSSING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (616, 'PB-00263', 'B. PENGGANTIAN LIFT ON', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (617, 'PB-00264', 'B. PENGGANTIAN STORAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (618, 'PB-00265', 'B. PENGGANTIAN FUMIGASI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (619, 'PB-00266', 'B. PENGGANTIAN HANDLING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (620, 'PB-00267', 'B. PENGGANTIAN KITE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (621, 'PB-00268', 'B. PENGGANTIAN THC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (622, 'PB-00269', 'B. PENGGANTIAN SEAL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (623, 'PB-00270', 'B. PENGGANTIAN LIFT OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (624, 'PB-00271', 'B. PENGGANTIAN LATE FINAL SI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (625, 'PB-00272', 'B. PENGGANTIAN PEB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (626, 'PB-00273', 'B. PENGGANTIAN OCEAN FREIGHT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (627, 'PB-00274', 'B. PENGGANTIAN PROFIT SHARE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (628, 'PB-00275', 'LOW SURFUR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (629, 'PB-00276', 'ENTRY + EXPORT SUMMARY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (630, 'PB-00277', 'B. PENGGANTIAN CLOSSING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (631, 'PB-00278', 'B. PENGGANTIAN LIFT ON/LIFT OFF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (632, 'PB-00279', 'DESTINATION CERTIFICATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (633, 'PB-00280', 'KURANG BAYAR TRUCKING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (634, 'PB-00281', 'EQUIPMENT MANAGEMENT IMPORT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (635, 'PB-00282', 'TEMBAK NPE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (636, 'PB-00283', 'SURVEY CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (637, 'PB-00284', 'PARKIR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (638, 'PB-00285', 'AFR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (639, 'PB-00286', 'BATAL DOCUMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (640, 'PB-00287', 'CSR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (641, 'PB-00288', 'PCS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (642, 'PB-00289', 'ADM - IMPORT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (643, 'PB-00290', 'CIC DESTINATION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (644, 'PB-00291', 'PENGIRIMAN DOCUMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (645, 'PB-00292', 'BATAL CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (646, 'PB-00293', 'VGM WEIGHTING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (647, 'PB-00294', 'VGM CERTIFICATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (648, 'PB-00295', 'NPE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (649, 'PB-00296', 'BIAYA CLOSING DOCUMENT', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (650, 'PB-00297', 'STICKER IMO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (651, 'PB-00298', 'BAF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (652, 'PB-00299', 'TEMBAK SEAL', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (653, 'PB-00300', 'B. SURAT PENGANTAR RE-DRESS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (654, 'PB-00301', 'BIAYA SURAT PENGANTAR RE-DRESS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (655, 'PB-00302', 'REPLAY COST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (656, 'PB-00303', 'OUTPORT ADDITIONAL ORIGIN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (657, 'PB-00304', 'PPN MASUKAN FUMIGASI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (658, 'PB-00305', 'EXPORT DECLARATION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (659, 'PB-00306', 'BIAYA DOCUMENT REDRESS MANIFEST', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (660, 'PB-00307', 'REPO ISI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (661, 'PB-00308', 'REPO KOSONGAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (662, 'PB-00309', 'BIAYA OUTPORT ADDITIONAL DESTINATION', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (663, 'PB-00310', 'BIAYA PENGELUARAN SYAHBANDAR', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (664, 'PB-00311', 'BIAYA PENGURUSAN CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (665, 'PB-00312', 'BIAYA TIMBANG CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (666, 'PB-00313', 'PENGIRIMAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (667, 'PB-00314', 'BIAYA LAS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (668, 'PB-00315', 'LATE CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (669, 'PB-00316', 'PPN MASUKAN LATE CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (670, 'PB-00317', 'ACC PLANNER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (671, 'PB-00318', 'BIAYA KRANI GATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (672, 'PB-00319', 'KULI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (673, 'PB-00320', 'DDF', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (674, 'PB-00321', 'LATE COMING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (675, 'PB-00322', 'PRINT B/L', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (676, 'PB-00323', 'TALLY', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (677, 'PB-00324', 'HANDLING CUSTOM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (678, 'PB-00325', 'CGC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (679, 'PB-00326', 'FSC', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (680, 'PB-00327', 'CCB', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (681, 'PB-00328', 'EQUIPMENT EXPORT DEMMURAGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (682, 'PB-00329', 'HAZARDOUS CARGO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (683, 'PB-00330', 'PPN MASUKAN HAZARDOUS CARGO', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (684, 'PB-00331', 'CV. GRAND EAGER GENSET', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (685, 'PB-00332', 'TIMBANGAN KOSONG', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (686, 'PB-00333', 'LSS', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (687, 'PB-00334', 'ADMINISTRASI', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (688, 'PB-00335', 'HAZARDOUS CERTIFICATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (689, 'PB-00336', 'PPN HAZARDOUS CERTIFICATE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (690, 'PB-00337', 'Additional', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (691, 'PB-00338', 'BIAYA TAMBAHAN', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (692, 'PB-00339', 'REPAIR CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (693, 'PB-00340', 'PENITIPAN CONTAINER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (694, 'PB-00341', 'RENUMBER', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (695, 'PB-00342', 'FREIGHT SURCHARGE', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (696, 'PB-00343', 'BIAYA CLEANING', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (697, 'PB-00344', 'BIAYA TELLY SHEET', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (698, 'PB-00345', 'BIAYA PENGIRIM', NULL, 'payable', NULL, NULL, NULL);
INSERT INTO `master_documents` VALUES (699, 'PB-00346', 'BIAYA PENGIRIMAN', NULL, 'payable', NULL, NULL, NULL);
